package modelo;
// Generated 9/04/2016 10:24:29 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idUsuario;
     private Usuario usuario;
     private Date fechaNacimientoAlumno;

    public Alumno() {
    }

	
    public Alumno(Usuario usuario) {
        this.usuario = usuario;
    }
    public Alumno(Usuario usuario, Date fechaNacimientoAlumno) {
       this.usuario = usuario;
       this.fechaNacimientoAlumno = fechaNacimientoAlumno;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaNacimientoAlumno() {
        return this.fechaNacimientoAlumno;
    }
    
    public void setFechaNacimientoAlumno(Date fechaNacimientoAlumno) {
        this.fechaNacimientoAlumno = fechaNacimientoAlumno;
    }




}


