package modelo;
// Generated 9/04/2016 12:14:27 AM by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idUsuario;
     private Usuario usuario;
     private Integer fechaNacimientoAlumno;

    public Alumno() {
    }

	
    public Alumno(Usuario usuario) {
        this.usuario = usuario;
    }
    public Alumno(Usuario usuario, Integer fechaNacimientoAlumno) {
       this.usuario = usuario;
       this.fechaNacimientoAlumno = fechaNacimientoAlumno;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getFechaNacimientoAlumno() {
        return this.fechaNacimientoAlumno;
    }
    
    public void setFechaNacimientoAlumno(Integer fechaNacimientoAlumno) {
        this.fechaNacimientoAlumno = fechaNacimientoAlumno;
    }




}


