package modelo;
// Generated 9/04/2016 10:24:29 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alumno generated by hbm2java
 * Clase para representa un alumno. Un alumno se caracteriza por los datos 
 * básicos de un usuario más la fecha de nacimiento.
 */
public class Alumno  implements java.io.Serializable {

    /* ID del usuario. */
    private int idUsuario;
    /* Usuario. */
    private Usuario usuario;
    /* Fecha de nacimiento del usuario. */
    private Date fechaNacimientoAlumno;
    
    /**
     * Constructor por omisión de un alumno.
     */
    public Alumno() {
    }

    /**
     * Constructor a partir de un parámetro.
     * @param usuario Usuario del que hereda.
     */
    public Alumno(Usuario usuario) {
        this.usuario = usuario;
    }
    
    /**
     * Constructor a partir de dos parámetros.
     * @param usuario Usuario del que hereda.
     * @param fechaNacimientoAlumno Fecha de nacimiento del alumno.
     */
    public Alumno(Usuario usuario, Date fechaNacimientoAlumno) {
       this.usuario = usuario;
       this.fechaNacimientoAlumno = fechaNacimientoAlumno;
    }
   
    /**
     * Método que obtiene el id del alumno.
     * @return id del alumno.
     */
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    /**
     * Método que modifica el id del usuario
     * @param idUsuario Nuevo id.
     */
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    /**
     * Método que obtiene el usuario del que hereda.
     * @return Usuario del que hereda.
     */
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    /**
     * Método que modifica el usuario.
     * @param usuario Nuevo usuario.
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    /**
     * Método que obtiene la fecha de nacimiento del alumno.
     * @return Fecha de nacimiento del alumno.
     */
    public Date getFechaNacimientoAlumno() {
        return this.fechaNacimientoAlumno;
    }
    
    /**
     * Método que modifica la fecha de nacimiento del alumno.
     * @param fechaNacimientoAlumno Nueva fecha de nacimiento.
     */
    public void setFechaNacimientoAlumno(Date fechaNacimientoAlumno) {
        this.fechaNacimientoAlumno = fechaNacimientoAlumno;
    }
}
