package modelo;
// Generated 9/04/2016 10:24:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private int idMateria;
     private String nombreMateria;
     private Integer areaMateria;
     private Set tutorMaterias = new HashSet(0);

    public Materia() {
    }

	
    public Materia(int idMateria, String nombreMateria) {
        this.idMateria = idMateria;
        this.nombreMateria = nombreMateria;
    }
    public Materia(int idMateria, String nombreMateria, Integer areaMateria, Set tutorMaterias) {
       this.idMateria = idMateria;
       this.nombreMateria = nombreMateria;
       this.areaMateria = areaMateria;
       this.tutorMaterias = tutorMaterias;
    }
   
    public int getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public Integer getAreaMateria() {
        return this.areaMateria;
    }
    
    public void setAreaMateria(Integer areaMateria) {
        this.areaMateria = areaMateria;
    }
    public Set getTutorMaterias() {
        return this.tutorMaterias;
    }
    
    public void setTutorMaterias(Set tutorMaterias) {
        this.tutorMaterias = tutorMaterias;
    }




}


