package modelo;
// Generated 9/04/2016 12:14:27 AM by Hibernate Tools 4.3.1



/**
 * TutorMateria generated by hbm2java
 */
public class TutorMateria  implements java.io.Serializable {


     private int idUsuario;
     private Materia materia;
     private Tutor tutor;

    public TutorMateria() {
    }

    public TutorMateria(Materia materia, Tutor tutor) {
       this.materia = materia;
       this.tutor = tutor;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Tutor getTutor() {
        return this.tutor;
    }
    
    public void setTutor(Tutor tutor) {
        this.tutor = tutor;
    }




}


